package com.app.maldroid.mlmodel

import android.content.pm.PackageInfo
import android.content.pm.PackageManager
import com.app.maldroid.data.model.MLAPKScanner

object FeatureMapper {
    val featureList = listOf(
        "transact",
        "onServiceConnected",
        "bindService",
        "attachInterface",
        "ServiceConnection",
        "android.os.Binder",
        "com.android.launcher.permission.uninstall_shortcut",
        "android.permission.read_sync_settings",
        "android.permission.write_sync_settings",
        "android.permission.authenticate_accounts",
        "android.permission.manage_accounts",
        "com.android.launcher.permission.install_shortcut",
        "android.permission.read_logs",
        "android.permission.use_credentials",
        "Ljava.lang.Class.getCanonicalName",
        "SEND_SMS",
        "Ljava.lang.Class.getMethods",
        "Ljava.lang.Class.cast",
        "Ljava.net.URLDecoder",
        "android.content.pm.Signature",
        "android.permission.get_accounts",
        "READ_PHONE_STATE",
        "ClassLoader",
        "Landroid.content.Context.unregisterReceiver",
        "Ljava.lang.Class.getField",
        "getBinder",
        "Landroid.content.Context.registerReceiver",
        "android.permission.read_phone_state",
        "android.telephony.SmsManager",
        "GET_ACCOUNTS",
        "android.permission.access_coarse_location",
        "Ljava.lang.Class.getDeclaredField",
        "RECEIVE_SMS",
        "READ_SMS",
        "Ljavax.crypto.spec.SecretKeySpec",
        "android.permission.access_wifi_state",
        "getCallingUid",
        "android.intent.action.BOOT_COMPLETED",
        "KeySpec",
        "DexClassLoader",
        "android.content.pm.PackageInfo",
        "HttpGet.init",
        "MANAGE_ACCOUNTS",
        "USE_CREDENTIALS",
        "SecretKey",
        "TelephonyManager.getLine1Number",
        "Ljava.lang.Class.getMethod",
        "System.loadLibrary",
        "android.intent.action.SEND",
        "Ljavax.crypto.Cipher",
        "android.permission.write_external_storage",
        "READ_SYNC_SETTINGS",
        "WRITE_SMS",
        "Runtime.getRuntime",
        "CAMERA",
        "mount",
        "AUTHENTICATE_ACCOUNTS",
        "TelephonyManager.getSubscriberId",
        "WRITE_SYNC_SETTINGS",
        "Ljava.lang.Object.getClass",
        "INTERNET",
        "Ljava.lang.Class.forName",
        "WRITE_HISTORY_BOOKMARKS",
        "android.intent.action.PACKAGE_REPLACED",
        "READ_HISTORY_BOOKMARKS",
        "INSTALL_PACKAGES",
        "android.telephony.gsm.SmsManager",
        "Binder",
        "RECORD_AUDIO",
        "android.intent.action.SEND_MULTIPLE",
        "IBinder",
        "android.os.IBinder",
        "URLClassLoader",
        "NFC",
        "TelephonyManager.getDeviceId",
        "MODIFY_AUDIO_SETTINGS",
        "android.intent.action.TIME_SET",
        "abortBroadcast",
        "BROADCAST_STICKY",
        "ACCESS_LOCATION_EXTRA_COMMANDS",
        "BIND_REMOTEVIEWS",
        "getCallingPid",
        "android.intent.action.PACKAGE_REMOVED",
        "WRITE_APN_SETTINGS",
        "android.permission.vibrate",
        "READ_PROFILE",
        "READ_SYNC_STATS",
        "WAKE_LOCK",
        "RECEIVE_BOOT_COMPLETED",
        "createSubprocess",
        "android.intent.action.TIMEZONE_CHANGED",
        "Ljava.lang.Class.getPackage",
        "RESTART_PACKAGES",
        "android.permission.access_fine_location",
        "android.permission.bluetooth",
        "android.intent.action.PACKAGE_ADDED",
        "chmod",
        "android.intent.action.ACTION_POWER_DISCONNECTED",
        "Ljava.lang.Class.getDeclaredClasses",
        "PathClassLoader",
        "android.permission.wake_lock",
        "android.permission.bluetooth_admin",
        "TelephonyManager.getCallState",
        "TelephonyManager.getSimSerialNumber",
        "BLUETOOTH",
        "READ_CALENDAR",
        "Runtime.load",
        "READ_EXTERNAL_STORAGE",
        "TelephonyManager.getSimCountryIso",
        "READ_CALL_LOG",
        "SUBSCRIBED_FEEDS_WRITE",
        "VIBRATE",
        "sendMultipartTextMessage",
        "android.intent.action.ACTION_SHUTDOWN",
        "HttpPost.init",
        "Ljava.lang.Class.getClasses",
        "ACCESS_NETWORK_STATE",
        "TelephonyManager.isNetworkRoaming",
        "PackageInstaller",
        "WRITE_CALENDAR",
        "remount",
        "SUBSCRIBED_FEEDS_READ",
        "sendDataMessage",
        "HttpUriRequest",
        "CHANGE_WIFI_MULTICAST_STATE",
        "chown",
        "MASTER_CLEAR",
        "android.intent.action.PACKAGE_DATA_CLEARED",
        "android.permission.read_external_storage",
        "GET_TASKS",
        "android.permission.record_audio",
        "GLOBAL_SEARCH",
        "DELETE_PACKAGES",
        "WRITE_CALL_LOG",
        "UPDATE_DEVICE_STATS",
        "android.intent.action.PACKAGE_CHANGED",
        "REORDER_TASKS",
        "WRITE_USER_DICTIONARY",
        "BIND_INPUT_METHOD",
        "android.permission.access_network_state",
        "SET_WALLPAPER",
        "DELETE_CACHE_FILES",
        "android.intent.action.NEW_OUTGOING_CALL",
        "divideMessage",
        "WRITE_PROFILE",
        "Runtime.exec",
        "CALL_PRIVILEGED",
        "READ_USER_DICTIONARY",
        "android.permission.camera",
        "BATTERY_STATS",
        "android.permission.get_tasks",
        "READ_SOCIAL_STREAM",
        "PROCESS_OUTGOING_CALLS",
        "BIND_WALLPAPER",
        "ACCESS_COARSE_LOCATION",
        "android.intent.action.SENDTO",
        "DUMP",
        "RECEIVE_WAP_PUSH",
        "BLUETOOTH_ADMIN",
        "REBOOT",
        "WRITE_SETTINGS",
        "TelephonyManager.getNetworkOperator",
        "SET_TIME",
        "WRITE_SOCIAL_STREAM",
        "BIND_DEVICE_ADMIN",
        "android.permission.broadcast_sticky",
        "/system/bin",
        "IRemoteService",
        "KILL_BACKGROUND_PROCESSES",
        "MessengerService",
    )

    fun mapToFeatureVector(extractedFeatures: MLAPKScanner.MLFeatures): Map<String, Int> {
        val allTextData = buildString {
            append(extractedFeatures.permissions.joinToString(" "))
            append(extractedFeatures.apiCalls.joinToString(" "))
            append(extractedFeatures.intentFilters.joinToString(" "))
            append(extractedFeatures.nativeLibraries.joinToString(" "))
            append(extractedFeatures.suspiciousStrings.joinToString(" "))
        }.lowercase()

        return featureList.associateWith { feature ->
            if (allTextData.contains(feature.lowercase())) 1 else 0
        }
    }
}